name: CI/CD Nginx Docker

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Vérifier les fichiers essentiels
        run: |
          test -f Dockerfile
          test -f nginx.conf
          test -f index.html
          test -f background.png

      - name: Construire l'image Docker
        run: docker build -t macron-nginx .

      - name: Tester la configuration Nginx
        run: docker run --rm macron-nginx nginx -t

      - name: Démarrer le conteneur
        run: docker run -d --name macron-nginx-test -p 8080:80 macron-nginx

      - name: Tester la réponse HTTP
        run: |
          sleep 3
          curl -f http://localhost:8080

      - name: Tester endpoint /health
        run: curl -f http://localhost:8080/health

      - name: Nettoyer le conteneur
        if: always()
        run: |
          docker stop macron-nginx-test || true
          docker rm macron-nginx-test || true

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Connexion à GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construire et publier l'image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/malezzblezz/macronmel:${{ github.sha }}
            ghcr.io/malezzblezz/macronmel:latest

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Validation manuelle avant déploiement
        run: echo "Déploiement validé manuellement"

      - name: Déploiement simulé
        run: |
          echo "Image prête à déployer : ghcr.io/malezzblezz/macronmel:${{ github.sha }}"
